BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "config" (
	"BOT_TOKEN"	TEXT NOT NULL,
	"TON_API"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "senders" (
	"collection_address"	TEXT NOT NULL,
	"telegram_id"	INTEGER NOT NULL
);
COMMIT;
