BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "config" (
	"BOT_TOKEN"	TEXT NOT NULL DEFAULT 123,
	"TONCENTER_API"	TEXT NOT NULL DEFAULT 123,
	"TON_API"	TEXT NOT NULL DEFAULT 123
);
CREATE TABLE IF NOT EXISTS "senders" (
	"collection_address"	TEXT NOT NULL,
	"telegram_id"	INTEGER NOT NULL,
	"last_time"	INTEGER NOT NULL DEFAULT 0,
	"id"	INTEGER,
	"telegram_user"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);
COMMIT;
